### ISSUE TITLE
E164 method US only

### ISSUE THREAD

**Issue by jaredmoody** [jayywolff/twilio-verify-devise#3]
`TwilioVerifyService.e164_format` is a one-liner that provides very little value, but makes this plugin unusable for anyone outside the US.

We have customers outside the US, so can't use this as-is.

How about just removing it and making a note in the README that the phone number provided needs to be validated to be in  E164 format?

**Comment by jayywolff** [comment]
Yeah i need to re-visit non US phone number support, I don't want to remove this method as this will introduce breaking changes for some apps.

I planned to swap out the hardcoded US format with a more versatile e164 formatting ruby gem like [hexorx/e164](https://github.com/hexorx/e164)
